# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{eztime}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Scharf"]
  s.date = %q{2015-02-27}
  s.description = %q{Easier date/time manipulation}
  s.email = %q{scharfie@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.textile"
  ]
  s.files = [
    "LICENSE.txt",
    "README.textile",
    "Rakefile",
    "VERSION",
    "eztime.gemspec",
    "init.rb",
    "install.rb",
    "lib/eztime.rb",
    "test/helper.rb",
    "test/test_eztime.rb"
  ]
  s.homepage = %q{http://github.com/scharfie/eztime}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Easier date/time manipulation}
end

